### ISSUE TITLE
ASU-Mayo Clinic Colonoscopy Video数据集如何获取？

### ISSUE THREAD

**Issue by moon6666** [lingyunwu14/STFT#2]
您好，请问本文所提到的ASU-Mayo Clinic Colonoscopy Video数据集该如何获取呢？在该数据集的网址https://polyp.grand-challenge.org/AsuMayo/ 中并未提及该数据集所有者的邮箱，请问您能帮帮我，提供一下该作者的邮箱或者其他联系方式吗？

**Comment by lingyunwu14** [comment]
The ASU-Mayo Clinic Colonoscopy Video (c) Database is copyrighted. If you are interested in using this database, please contact Prof. Jianming Liang at Arizona State University.

**Comment by lingyunwu14** [comment]
The ASU-Mayo Clinic Colonoscopy Video (c) Database is copyrighted. If you are interested in using this database, please contact Prof. Jianming Liang at Arizona State University.
